// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"github.com/labstack/echo/v4"
)

// Injectors from injection.go:

func NewApp() *echo.Echo {
	echoEcho := echo.New()
	return echoEcho
}
